name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        run: |
          sudo xcode-select -s $(ls -d /Applications/Xcode*.app | sort -V | tail -1)
          xcodebuild -version

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and test
        run: |
          set -o pipefail
          xcodebuild test \
            -workspace Batrider.xcodeproj/project.xcworkspace \
            -scheme Vehicle \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            -resultBundlePath TestResults \
            -quiet \
            clean test | tee xcodebuild.log | xcpretty
        timeout-minutes: 15
